# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15fd2bee13f65d3e850fcee1a1e9ae9c7584051aafec945bead5846e7ff53ea6dacda41c1681762c0f350b6b2cb646c2553e5dd117d1d5ad3a8f01b9599705ce

test:
  secret_key_base: c5172be7909b348bedfc32392c71abc5cb927fa047dfccdf0787ae0239427ee9a383540d6d29379ee9a1bf53c4684610e2762aa8168424e5c97d3cfe5e332248

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
